server_name v.i18n.site;
include head/resolver.cn.conf;
include ssl/i18n.site.conf;
location / {
  include head/proxy.conf;
  proxy_pass http://v-i18n;
  proxy_cache v-i18n;
  proxy_hide_header "cache-control";
  add_header cache-control "max-age=6";
  proxy_method GET;
  set $bypass 0;
  set $auth_basic off;
  set $auth_basic_user_file "";

  if ($request_method = POST) {
    set $bypass 1;
    set $auth_basic "-";
    set $auth_basic_user_file "/root/i18n/conf/nginx/v.i18n.site.pwd";
  }
  proxy_cache_bypass $bypass;
  auth_basic $auth_basic;
  auth_basic_user_file $auth_basic_user_file;
  proxy_set_header Authorization "";
}
