version: '3'

services:
  nginx:
    container_name: test-nginx
    image:  3tisite/nginx
    restart: always
    volumes:
      - /:/www
      - ./log/nginx:/var/log/nginx
      - ./nginx:/etc/nginx
    ports:
      - 80:80
      - 8023:8023
      - 443:443
      - 443:443/udp
    extra_hosts:
      - "host.docker.internal:host-gateway"
