include header/access.conf;

proxy_buffering Off;
proxy_buffers 32 1m;
proxy_buffer_size 512k;
proxy_busy_buffers_size 16m;

proxy_next_upstream error timeout http_502 http_503 http_504 non_idempotent;
proxy_next_upstream_tries 3;
proxy_redirect off;
proxy_send_timeout 300s;
proxy_connect_timeout 300s;
proxy_read_timeout 300s;
proxy_set_header Host $host;

# 前面可能有cdn，用X-Real-IP会导致问题
# proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_intercept_errors off;

client_max_body_size        128m;
client_body_buffer_size     4m;
