#!/usr/bin/env bash

set -ex

SQL="CREATE DATABASE IF NOT EXISTS $MYSQL_DB DEFAULT CHARACTER SET binary;\
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PWD';\
GRANT ALL PRIVILEGES ON $MYSQL_DB.* TO '$MYSQL_USER'@'%';\
DROP DATABASE IF EXISTS test;\
FLUSH PRIVILEGES;"

sudo -u mysql mysql -e "$SQL"
