---
- name: 安装软件并配置 / Install software and configure
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: 更新包缓存 / Update package cache
      apt:
        update_cache: yes

    - name: 卸载 vim（如果存在）/ Uninstall vim (if present)
      apt:
        name: vim
        state: absent
        purge: yes
        autoremove: yes

    - name: 安装软件包 / Install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - neovim
        - zsh
        - tmux
        - mosh
        - git

    - name: 将默认 shell 设置为 zsh / Set default shell to zsh
      shell: chsh -s $(which zsh) {{ ansible_user_id }}
      become: yes
      become_user: "{{ ansible_user_id }}"

    - name: 使用 update-alternatives 将 nvim 设置为 vim 和 vi / Set nvim as vim and vi using update-alternatives
      alternatives:
        name: "{{ item }}"
        path: /usr/bin/nvim
      loop:
        - vim
        - vi
