---
- name: 安装软件并配置 / Install software and configure
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: 更新包缓存 / Update package cache
      apt:
        update_cache: yes

    - name: 卸载 vim（如果存在）/ Uninstall vim (if present)
      apt:
        name: vim
        state: absent
        purge: yes
        autoremove: yes

    - name: 安装软件包 / Install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - neovim
        - zsh
        - tmux
        - mosh
        - git
        - rsync
        - openssh-client
        - eza
        - bat

    - name: 设置StrictHostKeyChecking / Set StrictHostKeyChecking
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^StrictHostKeyChecking'
        line: "StrictHostKeyChecking accept-new"
        create: yes
        insertafter: EOF

    - name: 设置HashKnownHosts / Set HashKnownHosts
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^HashKnownHosts'
        line: "HashKnownHosts no"
        create: yes
        insertafter: EOF

    - name: 禁止root用密码登录 / Disable root login with password
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin prohibit-password"
        create: yes
        insertafter: EOF

    - name: 重启SSH服务 / Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: 代码库指纹 / Code repository fingerprints
      ansible.builtin.shell: |
        ssh-keygen -R {{ item }}
        ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
      with_items:
        - gitlab.com
        - github.com
        - bitbucket.org
        - atomgit.com
        - gitee.com
      register: result
      until: result.rc == 0
      retries: 6

    - name: 将默认 shell 设置为 zsh / Set default shell to zsh
      shell: chsh -s $(which zsh) {{ ansible_user_id }}
      become: yes
      become_user: "{{ ansible_user_id }}"

    - name: 使用 update-alternatives 将 nvim 设置为 vim 和 vi / Set nvim as vim and vi using update-alternatives
      alternatives:
        name: "{{ item }}"
        path: /usr/bin/nvim
      loop:
        - vim
        - vi

    - name: 清理APT缓存 / Clean APT Cache
      apt:
        autoclean: yes
        clean: yes

    - name: 清理旧的内核 / Clean Old Kernels
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution == "Ubuntu"
