- name: 安装软件 / Install soft
  gather_facts: no
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: 安装编译工具链 / Install build tools
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - mold
        - clang

    - name: 同步脚本 / Sync scripts
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/sh/"
        dest: /tmp/sh/
        recursive: yes

    - name: 运行 setup.sh 脚本 / Run setup.sh script
      ansible.builtin.command: ./setup.sh
      args:
        chdir: /tmp/sh

    - name: 删除 /tmp/rust/target 目录 / Remove /tmp/rust/target directory
      file:
        path: /tmp/rust/target
        state: absent
