server_name upv.i18n.site;
resolver  1.1.1.1 1.0.0.2;
ssl_certificate_key /opt/ssl/i18n.site_ecc/i18n.site.key;
ssl_certificate /opt/ssl/i18n.site_ecc/fullchain.cer;
location / {
  proxy_set_header Host upv.x01.site;
  include head/proxy.https.conf;
  proxy_pass https://upv.x01.site;
  proxy_hide_header "alt-svc";
  proxy_hide_header "cf-ray";
  proxy_hide_header "cf-placement";
}
