location / {
include head/proxy.x_forwarded_for.conf;
proxy_pass http://i18n;
}

location ~ ^/ws/([\w-]+)/ {
# access_log /var/log/nginx/ws.i18n.dev.access.log with_body;
set $c $1;
include head/ws.conf;
proxy_pass http://i18n-c;
}


location ~ ^/tran/([\w-]+) {
# access_log /var/log/nginx/ws.i18n.dev.access.log with_body;
set $c $1;
proxy_pass http://i18n-c;
}
