- name: mariadb 配置 / mariadb config
  gather_facts: yes
  hosts: mariadb_1_master_2_slave
  become: yes
  become_user: root

  tasks:
    - name: 同步安装脚本 / Sync setup script
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/../../mariadb"
        dest: /opt/ops/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--chown=root:root"

    - name: 同步 mariadb 配置 / Synchronize mariadb config
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/../../conf/mariadb"
        dest: /etc/ops/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--chown=root:root"

    - name: 获取所有主机名 / Get all hostnames
      set_fact:
        all_hostnames: "{{ ansible_play_hosts | map('extract', hostvars, 'inventory_hostname') | list }}"

    - name: 运行本地脚本并传入主机名 / Run local script with hostnames
      local_action:
        module: shell
        cmd: "./ip_li.sh mariadb {{ all_hostnames | join(' ') }}"
      delegate_to: localhost
      run_once: true
      become: no

    - name: 分发 ip_li.sh 文件到所有主机 / Distribute ip_li.sh file to all hosts
      copy:
        src: "{{ playbook_dir }}/../../conf/mariadb/ip_li.sh"
        dest: /etc/ops/mariadb/ip_li.sh
        mode: "0755"
        owner: "root"
        group: "root"
